name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled
jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport
    if: github.event.pull_request.merged == true
    steps:
      # For security reasons, we do not check out any code in this workflow
      - uses: tibdex/backport@e2ffd4c5a70730dfd19046859dfaf366e3de6466 # v1.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
