name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled
concurrency:
  # Skip intermediate builds: all builds except for builds on the `main` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
permissions:
  contents: write
  pull-requests: write
jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport
    if: github.event.pull_request.merged
    steps:
      # For security reasons, we do not check out any code in this workflow
      - uses: tibdex/backport@e2ffd4c5a70730dfd19046859dfaf366e3de6466 # v1.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
