---
name: ShellCheck
on:
  push:
    branches:
      - 'main'
      - 'release-*'
  pull_request:
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: ShellCheck
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run shellcheck on all .sh files
        shell: bash
        run: |
          failures=0
          while IFS= read -r -d '' file; do
              echo "Checking file '${file}'..."
              if ! shellcheck "${file}"; then
                  failures=$((failures + 1))
              fi
          done < <(find . -type f -name '*.sh' -print0)
          if [[ "${failures}" -gt 0 ]]; then
              echo "Shellcheck failed for ${failures} files."
          fi
          exit "${failures}"
